### PR TITLE
Update 1.logging-onto-cloud.md

### PR DESCRIPTION
**Pull request by darwinFailure**

### CODE REVIEW

**Comment by stephenturner** [comment]
this could be improved by either copying the instructions from the angus website or retaining the links giving full instructions.

**Comment by cjfields** [comment]
One problem: the edits fundamentally change the underlying infrastructure used in the example, from AWS to a local cloud setup called 'Sara'.  Other options:

* making the current instructions more generic and point to outside resources (possibly like @stephenturner mentions)
* a new doc in the repo for a local cloud setup.
* having a fork of the docs specific to your local HPC/cloud setup for your needs

**Comment by cjfields** [comment]
See also: Issue #7. @tracykteal cognizant as always :)

**Comment by tracykteal** [comment]
I think we can leave the default as Amazon and have parallel cloud lessons or a separate branch as in #7. @darwinFailure can you resubmit with this as a separate file, i.e. 1-logging-onto-cloud-sara.md  If it's really only the login that will change this will be fine. If other things in the lesson need to change to reflect local architecture though, it might be best to have a separate branch.

**Comment by darwinFailure** [comment]
Actually this pull request we are discussing on was made by mistake during the last datacarpentry hackaton. I will delete it now. Sorry for this.

**Pull request closed without merging**
