### PR TITLE
revamped single analysis lesson 

### PR DESCRIPTION
**Pull request by stephenturner**
Revamped and fleshed out single analysis lesson using dataCgen-qc (ami-3c1c3454) image tools and data. Runs FastQC on one of the read sets, trims data with trimmomatic, and re-runs fastqc as an exercise.

### CODE REVIEW

**Comment by ACharbonneau** [comment]
I think this looks good, but I'm not sure if we should let the original team for each section approve and do merges, or if we should just update things...

**Comment by stephenturner** [comment]
care to review, @cjfields @adina @devbioinfoguy ?

**Comment by cjfields** [comment]
Looks awesome to me @stephenturner !

**Comment by devbioinfoguy** [comment]
Very nice -- looks good to me as well. How will this dovetail with the "data wrangling" section? Or will this be it instead?

**Comment by ACharbonneau** [comment]
This is sort of a merge of data wrangling and cloud genomics. I'll have my re-jig of data wrangling up soon

**Comment by cjfields** [comment]
@ACharbonneau cool!  @devbioinfoguy I've already merged the changes, let me know if we should back them out.

**Comment by ACharbonneau** [comment]
You shouldn't have to, I'm going to dump my stuff in https://github.com/datacarpentry/wrangling-genomics

**Comment by cjfields** [comment]
works for me.  And thanks to you and @stephenturner for the updates :)

**Comment by devbioinfoguy** [comment]
So, it looks like we can start to remove those from this module. Not sure if we're going to keep most of this anyhow. More later.

**Comment by cjfields** [comment]
@devbioinfoguy We could always deprecate/archive this repo I suppose.

**Comment by devbioinfoguy** [comment]
Tracy & I are having a pow-wow tomorrow to get her guidance on the split personalities present in the repo. We'll use things here; just getting guidance on what's getting voted off the island. :-)

**Pull request merged**
