### PR TITLE
move instructions to main setup page

### PR DESCRIPTION
**Pull request by ErinBecker**
Please review and merge in conjuction with https://github.com/datacarpentry/genomics-workshop/pull/67

### CODE REVIEW

**Comment by ACharbonneau** [comment]
Hey Erin, I'm confused about this change. I have two main questions: 

- Why drop the selection box code if we're keeping both iplant and Amazon instructions?
- Why are we keeping very detailed instructions for iplant, but not for Amazon? It seems like most of our users would want the more detailed Amazon instructions, as that's the platform we teach them. But if we're reducing the overall detail, I think it would make more sense to scale back the iplant instructions and just refer them out to iplant in the same way you've edited the Amazon part.

**Comment by ErinBecker** [comment]
Hi @ACharbonneau, thanks for the questions. The other PR I linked to had more information about this change, but I should have included it here as well. Sorry for that.

You're absolutely correct that most of our users will be using AWS and that's the most relevant for them. That's the motivation behind moving those detailed instructions to the workshop homepage (https://datacarpentry.org/genomics-workshop/AMI-setup/index.html). I was worried that those instructions got buried in the rest of this material and wanted to make sure it was clear for people who are trying to set up their own instance. I also added a callout box at the top to make it more clear who would need to create their own instances and who should contact Carpentries staff to get an instance. 

My idea is that this new page on the workshop homepage will serve as the starting point for people wanting to set up their own instances [and are directed there from the setup page](https://datacarpentry.org/genomics-workshop/setup.html) and that the existing page on the cloud lesson will be for additional details that don't apply to everyone and for info on how to connect to other services. 

Please let me know what you think and if I can give any more clarification.

**Comment by ACharbonneau** [comment]
Right, I saw the reasoning in the other PR as well. I'm not particularly concerned that much of the AWS information was moved, rather that the changes make the page content really iPlant heavy and potentially confusing.
The callout is entirely about AWS and without the content choosing code, [Launching an instance on Atmosphere - These instructions are in beta and not fully tested!](https://github.com/datacarpentry/cloud-genomics/blob/be080156158cebb0b5e1ab0463aea94fd89be5e2/_extras/LaunchingInstances.md#launching-an-instance-on-atmosphere---these-instructions-are-in-beta-and-not-fully-tested) now appears right after the AWS content, with no introduction or context. It makes it seem like it's just the next step in the AWS instructions. I think that a general user isn't going to realize that the AWS section and iPlant section have nothing to do with one another.

There's a few possible solutions:
- add another "If you are" to the call out to specifically address the iPlant instructions
- remove iPlant entirely
- Move the iPlant instructions to their own page
- Add in an intro and context for iPlant (I am pretty sure this used to exist somewhere so it wouldn't need to be written from scratch) and probably also give it an "If you are"
- Re-add the selection code so the iPlant information only appears if you actively select it
- something else I haven't thought of

**Comment by ErinBecker** [comment]
Thanks for clarifying @ACharbonneau. I haven't been able to get lessons to render locally for a while (something broken in my ruby install), so I wasn't able to locally preview this. Thanks for checking that. I understand that it looks confusing without the platform selection script. I've tried to add that back in, but I'm not a whiz at HTML so would appreciate a second check if you have time. Thanks so much!

**Comment by ACharbonneau** [comment]
OK. I fixed the dialogue box code, so I think its' all working now. It might be good to have someone else double check if possible.

**Review by ACharbonneau — APPROVED** [review]

**Comment by ErinBecker** [comment]
Thanks @ACharbonneau! I'll give this a merge and make sure everything looks good.

**Comment by ErinBecker** [comment]
Everything is rendering ok for me. Thanks @ACharbonneau for helping me work through this one.

**Pull request merged**
