### PR TITLE
Update to styles v9.5.2

### PR DESCRIPTION
**Pull request by fmichonneau**
This pull request brings the latest version of the template to this repository. Release notes are available from the styles GitHub Repository. See [v9.5.1](https://github.com/carpentries/styles/releases/tag/v9.5.1) and [v9.5.2](https://github.com/carpentries/styles/releases/tag/v9.5.2). Deployment progress tracked in carpentries/styles#302.

### CODE REVIEW

**Review by ACharbonneau — APPROVED** [review]
I think this is fine

**Comment by ACharbonneau** [comment]
@fmichonneau Hi there. I merged in these changes yesterday (late, I know, but I was hoping another maintainer would look at it as well) and immediately got an email from GitHub that gh-pages no longer renders;
>The page build failed for the `gh-pages` branch with the following error:

>Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-builds/.

>For information on troubleshooting Jekyll see:

>  https://help.github.com/articles/troubleshooting-jekyll-builds

However, when I check the [site](http://www.datacarpentry.org/cloud-genomics/) nothing seems wrong. Do you have any idea what I should be looking for?

**Comment by fmichonneau** [comment]
no problem. Sorry for the issue. It looks like one of the file needed by the newer version of the template was missing in the repository. I added, and in the process upgraded you to the latest version of the lesson template. Let me know if you notice anything broken. Thanks!

**Comment by ACharbonneau** [comment]
Thanks!

**Pull request merged**
