### PR TITLE
remove password

### PR DESCRIPTION
**Pull request by ErinBecker**
These shouldn't be public, but should be shared by Instructors before the workshop.

### CODE REVIEW

**Comment by dvanic** [comment]
@ErinBecker, should this then be added to the instructor notes?

**Comment by ErinBecker** [comment]
@dvanic - No. Instructors receive log-in information from Carpentries staff when they are preparing to teach. For security and financial reasons, we shouldn't have this information posted publicly.

**Review by ACharbonneau — APPROVED** [review]
LGTM

**Comment by ErinBecker** [comment]
Thanks @ACharbonneau. I'll go ahead and merge this now.

**Pull request merged**
