### PR TITLE
adding Jason's connecting to the cloud in 5 minutes lesson

### PR DESCRIPTION
**Pull request by tracykteal**

### CODE REVIEW

**Comment by tracykteal** [comment]
@JasonJWilliamsNY thanks for the updates to this lesson! I want to add in the index.md with the nice lesson on logging on to the cloud. The _site files got in to the commit though. Could you take those out?

**Comment by JasonJWilliamsNY** [comment]
@tracykteal just to be clear, are you asking I delete _site?? BTW, my GH notifications are heavily muted, but I just happened to so this one so you may also want to email me.

**Comment by JasonJWilliamsNY** [comment]
@tracykteal just to be clear, you want me to delete the entire _site directory? Also, my GH notifications are heavily muted so you may also want to email me; I just happened to see this one.

**Comment by devbioinfoguy** [comment]
Followed command line instructions above with the following modifications:
- retained _config.yml
- retained _includes/rSetup.html
- retained lessons/0.cloud-introduction.Rmd
- removed _site/

-Bob

**Pull request merged**
