### PR TITLE
adding Open Science Grid paragraph

### PR DESCRIPTION
**Pull request by ChristinaLK**
Adding some information about the Open Science Grid as a resource - it's technically available through XSEDE, but it makes much more sense to access it on its own, as it doesn't have an allocation/hours limit the way other XSEDE resources do.

### CODE REVIEW

**Review by ACharbonneau — APPROVED** [review]
This is great, thank you!

**Comment by dvanic** [comment]
@ACharbonneau I just reread the "Which Cloud" page, and realised that a lot of the Open Science content is US-specific. I'm not sure, but should we:
1. Change the heading of the section to reflect this?
2. Add some wording around the fact that other countries will have different Open Science clouds (I'm hesitant to add details about them to the page, as details of the Australian and European ones change every 1-2 years, so maintaining the information will be a big challenge).?

**Comment by ACharbonneau** [comment]
I think that's a good idea. What do you think of this: https://github.com/datacarpentry/cloud-genomics/pull/98

**Comment by ChristinaLK** [comment]
@dvanic that's a great point and I thought of it as I was writing the paragraph.

**Pull request merged**
